#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/file
#
# IDENTIFICATION
#    src/backend/storage/file/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/file
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	buffile.o \
	copydir.o \
	datadir.o \
	fd.o \
	fileset.o \
	file_utils.o \
	reinit.o \
	sharedfileset.o

include $(top_srcdir)/src/backend/common.mk
