#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/ipc
#
# IDENTIFICATION
#    src/backend/ipc/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/ipc
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	interrupt.o \
	signal_handlers.o

include $(top_srcdir)/src/backend/common.mk
